from __future__ import annotations

import pytest

from ai_code_stack.filesystem import atomic_write_text, ensure_child, link_strategy, sha256


def test_link_strategy_windows_includes_junction():
    strategy = link_strategy("windows")
    assert "junction" in strategy
    assert strategy[0] == "junction"


def test_link_strategy_posix_has_no_junction():
    for name in ("macos", "linux"):
        strategy = link_strategy(name)
        assert "junction" not in strategy
        assert "symlink" in strategy


def test_ensure_child_accepts_nested_path(tmp_path):
    parent = tmp_path / "root"
    parent.mkdir()
    child = parent / "a" / "b.txt"
    ensure_child(parent, child)  # should not raise


def test_ensure_child_rejects_escape(tmp_path):
    parent = tmp_path / "root"
    parent.mkdir()
    outside = tmp_path / "outside.txt"
    with pytest.raises(ValueError):
        ensure_child(parent, outside)


def test_atomic_write_text_refuses_to_overwrite_non_generated_file(tmp_path):
    target = tmp_path / "manual.md"
    target.write_text("hand-written content", encoding="utf-8")
    with pytest.raises(FileExistsError):
        atomic_write_text(target, "GENERATED BY AI CODE STACK\ncontent")


def test_atomic_write_text_allows_overwriting_generated_file(tmp_path):
    target = tmp_path / "generated.md"
    target.write_text("GENERATED BY AI CODE STACK\nold", encoding="utf-8")
    atomic_write_text(target, "GENERATED BY AI CODE STACK\nnew")
    assert "new" in target.read_text(encoding="utf-8")


def test_sha256_is_deterministic(tmp_path):
    target = tmp_path / "file.txt"
    target.write_text("hello", encoding="utf-8")
    assert sha256(target) == sha256(target)
