from __future__ import annotations

import hashlib
import json
import os
import shutil
import tempfile
from pathlib import Path
from typing import Any


GENERATED_MARKER = "GENERATED BY AI CODE STACK"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def normalized(path: Path) -> str:
    return path.resolve(strict=False).as_posix()


def ensure_child(parent: Path, child: Path) -> None:
    parent_resolved = parent.resolve(strict=False)
    child_resolved = child.resolve(strict=False)
    try:
        child_resolved.relative_to(parent_resolved)
    except ValueError as exc:
        raise ValueError(f"unsafe path outside {parent_resolved}: {child_resolved}") from exc


def atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and GENERATED_MARKER not in path.read_text(encoding="utf-8-sig"):
        raise FileExistsError(f"refusing to overwrite non-generated file: {path}")
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(temp_name, path)
    finally:
        if os.path.exists(temp_name):
            os.unlink(temp_name)


def atomic_write_json(path: Path, payload: Any) -> None:
    content = f"{{\n  \"_generator\": \"{GENERATED_MARKER}\",\n"
    encoded = json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True)
    if not encoded.startswith("{"):
        raise TypeError("generated JSON root must be an object")
    atomic_write_text(path, content + encoded[1:] + "\n")


def link_strategy(platform_name: str) -> list[str]:
    if platform_name == "windows":
        return ["junction", "symlink", "controlled_copy"]
    return ["symlink", "controlled_copy"]


def copy_backup(source: Path, target: Path) -> None:
    if source.is_dir():
        shutil.copytree(source, target, dirs_exist_ok=True)
    elif source.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
